import { ClassificationType, BookFormat } from '../enums';
import { Bisacs } from './bisacs';

export interface Book {
  id: string;
  title: string;
  isbn: string;
  thumbnailSmallUrl: string;
  profilesImageUrl: string;
  maxGrade: number;
  minGrade: number;
  lightSailReady: boolean;
  premium: boolean;
  profiles: string[];
  authors: string[];
  genres: string[];
  topics: string[];
  series: string[];
  keywords: string[];
  categories: string[];
  religions: string[];
  lexile: number;
  publishers: string[];
  imprints: string[];
  deleted: boolean;
  classificationType: ClassificationType;
  totalPages: number;
  synopsis: string;
  format: BookFormat;
  language: string;
  bisacs: Bisacs[];
  bisacCodes: string[];
  bisacSubjects: string[];
  bisacFull: string[];
  isbns: (string | number)[];
  bios: string[];
  excerpts: string[];
  reviews: string[];
  audienceCodes: number[];
  publicationDate: string;
  isWorldBookBio: boolean;
  hasB2CEnabledProducts: boolean;
  libraryCollectionIds: string[];
  rank0: number;
  rank1: number;
  rank2: number;
  rank3: number;
  rank4: number;
  hasThumbnail: boolean;
  catalog: boolean;
  libraryIds: string[];
  appropriateLevelIds: string[];
  rated: boolean;
  noReligion: boolean;
  bookReadingLevel: number;
}
